name: Multi Event Workflow

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main

jobs:
    echo_basic_info:
        runs-on: ubuntu-latest
        steps:
            - name: "Echo Basic Information"
              run: |
                echo "REF: $GITHUB_REF"
                echo "Job ID: $GITHUB_JOB"
                echo "Action: $GITHUB_ACTION"
                echo "Actor: $GITHUB_ACTOR"