name: Time Logger

on:
    schedule:
        - cron: '*/5 * * * *'

jobs:
    log_current_time:
        runs-on: ubuntu-latest
        steps:
            - name: Echo current time
              run: echo "The current server time is ${date}"
